# Documentation https://s.apache.org/asfyaml
notifications:
  commits: commits@struts.apache.org
  # Send all issue emails (new, closed, comments) to issues@
  issues: issues@struts.apache.org
  # Send new/closed PR notifications to commits@
  pullrequests_status: notifications@struts.apache.org
  # Send individual PR comments/reviews to issues@
  pullrequests_comment: notifications@struts.apache.org
  # Link opened PRs with JIRA
  jira_options: link label worklog

github:
  del_branch_on_merge: true
  protected_branches:
    master: { }
  autolink_jira:
    - WW
  dependabot_alerts:  true
  dependabot_updates: true
