/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * This file was automatically generated by Autotag.  Please do not edit it manually.
 */
package org.apache.tiles.freemarker.template;

/**
 * This tag library provides Tiles tags.
 */
public class TilesFMModelRepository {

    /**
     * The "insertDefinition" directive.
     */
    private InsertDefinitionFMModel insertDefinition;

    /**
     * The "importAttribute" directive.
     */
    private ImportAttributeFMModel importAttribute;

    /**
     * The "setCurrentContainer" directive.
     */
    private SetCurrentContainerFMModel setCurrentContainer;

    /**
     * The "addListAttribute" directive.
     */
    private AddListAttributeFMModel addListAttribute;

    /**
     * The "getAsString" directive.
     */
    private GetAsStringFMModel getAsString;

    /**
     * The "insertAttribute" directive.
     */
    private InsertAttributeFMModel insertAttribute;

    /**
     * The "putAttribute" directive.
     */
    private PutAttributeFMModel putAttribute;

    /**
     * The "definition" directive.
     */
    private DefinitionFMModel definition;

    /**
     * The "addAttribute" directive.
     */
    private AddAttributeFMModel addAttribute;

    /**
     * The "putListAttribute" directive.
     */
    private PutListAttributeFMModel putListAttribute;

    /**
     * The "insertTemplate" directive.
     */
    private InsertTemplateFMModel insertTemplate;

    /**
     * Constructor.
     */
    public TilesFMModelRepository() {
        insertDefinition = new InsertDefinitionFMModel(new org.apache.tiles.template.InsertDefinitionModel());
        importAttribute = new ImportAttributeFMModel(new org.apache.tiles.template.ImportAttributeModel());
        setCurrentContainer = new SetCurrentContainerFMModel(new org.apache.tiles.template.SetCurrentContainerModel());
        addListAttribute = new AddListAttributeFMModel(new org.apache.tiles.template.AddListAttributeModel());
        getAsString = new GetAsStringFMModel(new org.apache.tiles.template.GetAsStringModel());
        insertAttribute = new InsertAttributeFMModel(new org.apache.tiles.template.InsertAttributeModel());
        putAttribute = new PutAttributeFMModel(new org.apache.tiles.template.PutAttributeModel());
        definition = new DefinitionFMModel(new org.apache.tiles.template.DefinitionModel());
        addAttribute = new AddAttributeFMModel(new org.apache.tiles.template.AddAttributeModel());
        putListAttribute = new PutListAttributeFMModel(new org.apache.tiles.template.PutListAttributeModel());
        insertTemplate = new InsertTemplateFMModel(new org.apache.tiles.template.InsertTemplateModel());
    }

    /**
     * Returns the "insertDefinition" directive.
     *
     * @return The "insertDefinition" directive.
     */
    public InsertDefinitionFMModel getInsertDefinition() {
        return insertDefinition;
    }

    /**
     * Returns the "importAttribute" directive.
     *
     * @return The "importAttribute" directive.
     */
    public ImportAttributeFMModel getImportAttribute() {
        return importAttribute;
    }

    /**
     * Returns the "setCurrentContainer" directive.
     *
     * @return The "setCurrentContainer" directive.
     */
    public SetCurrentContainerFMModel getSetCurrentContainer() {
        return setCurrentContainer;
    }

    /**
     * Returns the "addListAttribute" directive.
     *
     * @return The "addListAttribute" directive.
     */
    public AddListAttributeFMModel getAddListAttribute() {
        return addListAttribute;
    }

    /**
     * Returns the "getAsString" directive.
     *
     * @return The "getAsString" directive.
     */
    public GetAsStringFMModel getGetAsString() {
        return getAsString;
    }

    /**
     * Returns the "insertAttribute" directive.
     *
     * @return The "insertAttribute" directive.
     */
    public InsertAttributeFMModel getInsertAttribute() {
        return insertAttribute;
    }

    /**
     * Returns the "putAttribute" directive.
     *
     * @return The "putAttribute" directive.
     */
    public PutAttributeFMModel getPutAttribute() {
        return putAttribute;
    }

    /**
     * Returns the "definition" directive.
     *
     * @return The "definition" directive.
     */
    public DefinitionFMModel getDefinition() {
        return definition;
    }

    /**
     * Returns the "addAttribute" directive.
     *
     * @return The "addAttribute" directive.
     */
    public AddAttributeFMModel getAddAttribute() {
        return addAttribute;
    }

    /**
     * Returns the "putListAttribute" directive.
     *
     * @return The "putListAttribute" directive.
     */
    public PutListAttributeFMModel getPutListAttribute() {
        return putListAttribute;
    }

    /**
     * Returns the "insertTemplate" directive.
     *
     * @return The "insertTemplate" directive.
     */
    public InsertTemplateFMModel getInsertTemplate() {
        return insertTemplate;
    }
}
